#!/usr/bin/env tsx
/**
 * Auto-generate gymMachineLabels.ts from machines.json
 *
 * This script ensures that machine labels stay in sync with the machine library.
 * Run this script whenever machines.json is updated.
 *
 * Usage: npm run generate-labels
 */

import * as fs from 'fs';
import * as path from 'path';

interface MachineRecognition {
  visualPrompts: string[];
  labelId?: string;
  synonyms?: string[];
  keywords?: string[];
}

interface MachineDefinition {
  id: string;
  name: string;
  category: string;
  primaryMuscles: string[];
  secondaryMuscles?: string[];
  recognition?: MachineRecognition;
}

interface GymMachineLabel {
  id: string;
  name: string;
  prompt: string;
  synonyms: string[];
  category: string;
  keywords?: string[];
}

// Read machines.json
const machinesPath = path.join(__dirname, '../src/data/machines.json');
const machines: MachineDefinition[] = JSON.parse(fs.readFileSync(machinesPath, 'utf-8'));

// Generate labels from machines with recognition data
const labels: GymMachineLabel[] = machines
  .filter(machine => machine.recognition && machine.recognition.visualPrompts.length > 0)
  .map(machine => {
    const recognition = machine.recognition!;

    return {
      id: recognition.labelId || `${machine.id}_label`,
      name: machine.name,
      prompt: recognition.visualPrompts[0], // Use first visual prompt as main prompt
      synonyms: recognition.synonyms || [machine.name.toLowerCase()],
      category: machine.category,
      keywords: recognition.keywords || [],
    };
  });

// Generate TypeScript file content
const fileContent = `// Auto-generated from machines.json
// DO NOT EDIT THIS FILE MANUALLY
// Run 'npm run generate-labels' to regenerate
// Last generated: ${new Date().toISOString()}

export interface GymMachineLabel {
  id: string;
  name: string;
  prompt: string;
  synonyms: string[];
  category: string;
  keywords?: string[];
}

export const GYM_MACHINE_LABELS: GymMachineLabel[] = ${JSON.stringify(labels, null, 2)};

export function getGymMachineLabel(id: string): GymMachineLabel | undefined {
  return GYM_MACHINE_LABELS.find(label => label.id === id);
}
`;

// Write to gymMachineLabels.ts
const outputPath = path.join(__dirname, '../src/data/gymMachineLabels.ts');
fs.writeFileSync(outputPath, fileContent, 'utf-8');

console.log(`✅ Generated ${labels.length} labels from ${machines.length} machines`);
console.log(`📝 Output: ${outputPath}`);
